### ISSUE TITLE
Android build failed with 403 error from Maven gist

### ISSUE THREAD

**Issue by daniel-fs** [customerio/customerio-reactnative#114]
**SDK version:**
CustomerIO-ReactNative 2.2.0
React Native 0.71.4

**Environment:** Development and Production

**Describe the bug**
Just last week, my Android builds with RN 0.71 and CustomerIO-ReactNative 2.2.0 were working fine. However, starting from yesterday, I can no longer build my Android app due to a 403 error being returned from https://maven.gist.build/build/gist/maven-metadata.xml.

Nothing was changed in the gradle files nor in the project's dependencies during this time.

Tested without CustomerIO in my project and the app builds just fine as it doesn't need to fetch anything from maven.gist.build without it.

**Additional context**
Gradle build error:

```
* What went wrong:
Could not determine the dependencies of task ':customerio-reactnative:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':customerio-reactnative:debugCompileClasspath'.
   > Could not resolve build:gist:[3.1,4.0).
     Required by:
         project :customerio-reactnative > io.customer.android:messaging-in-app:3.3.2
      > Failed to list versions for build:gist.
         > Unable to load Maven meta-data from https://maven.gist.build/build/gist/maven-metadata.xml.
            > Could not HEAD 'https://maven.gist.build/build/gist/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for build:gist.
         > Unable to load Maven meta-data from https://maven.gist.build/build/gist/maven-metadata.xml.
            > Could not HEAD 'https://maven.gist.build/build/gist/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

My `android/build.gradle` file:

```
import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 22
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.20"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven {
            url 'https://sdk.uxcam.com/android/'
        }
        maven { url 'https://maven.gist.build' }
    }
}
```
Let me know if any further info is needed.

**Comment by Shahroz16** [comment]
Hey @daniel-fs, just checked the maven dependency of gist and it seems to be working. 

```
https://maven.gist.build/build/gist/maven-metadata.xml.
```

responding to 403 is normal. 

Can you please try 
```
rm -rf node_modules && yarn install && npx react-native run-android
```

also, you can check out the [sample app](https://github.com/customerio/amiapp-reactnative) to match `build.gradle` files?

**Comment by daniel-fs** [comment]
Hi @Shahroz16, thanks for the reply.

Tried removing my node_modules folder and reinstalling the packages. Also made the build.gradle file match the one on the sample app, and went through the README again to make sure I didn't miss anything - still get the same 403 Forbidden error in gradle that I posted above when building the app with the `npx react-native run-android` command.

Also tried switching gradle versions to no avail. Gradle seems unable to fetch the in-app messaging dependency from Maven Gist no matter what I do. The weirdest part here is that it only started happening yesterday without any changes to the code.

**Comment by mrehan27** [comment]
Hey @daniel-fs Thanks for the confirmation. It looks like you have setup everything correctly. But gradle is, somehow, unable to fetch data from these repositories. Can you please try the following:

- Try cleaning your build folders and Android Studio cache
- Switch to another network and/or try building on another machine. Also, make sure there isn't any proxy or network/antivirus restrictions preventing gradle to fetch data from these repositories
- If nothing works, exit Android Studio, stop all gradle tasks and clean your gradle cache from machine and then rebuild. It might take long to rebuild your gradle projects after that, but should cleanup any local files and fetch the latest ones for you

**Comment by daniel-fs** [comment]
Hello @mrehan27, thanks for the suggestions.

I tried all of them, and I still get the same error. Even cleared the caches on my other computer, didn't help either. Asked some of my colleagues to also try to build the app on their machines and their networks, and they're also getting the same error. I also made sure any sort of firewalls and antiviruses were turned off. Nothing helped :/

**Comment by mrehan27** [comment]
Sorry to hear this @daniel-fs. Can you please also try opening the [maven-metadata](https://maven.gist.build/build/gist/maven-metadata.xml) file and see if you are able to download it on your machine using browser?

**Comment by Shahroz16** [comment]
@daniel-fs thank you for your patience with us while we try to help debug. Would it be possible for you to try on a different machine? because the [link](https://maven.gist.build/build/gist/maven-metadata.xml) opens for us and Gradle is able to pull the latest version for us. 

I suspect its a network issue or something else for this machine. The same maven dependency is being used in all our clients, Android/RN/Flutter and this problem is just being faced by you. 

If there is anything we can do to boost your confidence, please let me know. I am attaching a [video](https://user-images.githubusercontent.com/4658866/225419985-b5d1d3b8-394d-4a59-82ed-41472920a861.mov
) of how entering this link downloads the meta data file for us.

**Comment by daniel-fs** [comment]
@Shahroz16 and @mrehan27 thank you for your help and your patience. I asked more work colleagues in different locations and with different ISPs to try the links. It worked for them.

I'm now using a VPN service to build the app and it worked! Never would've thought my ISP would be having problems with Maven Gist in particular. All the people from my team in my area are affected with this same problem. It's also the reason it wasn't working in any of our machines.

Closing this issue as it's technically solved. Thanks again for all the suggestions!

**Comment by plahteenlahti** [comment]
Hey, this is happening to me as well. Worked fine a week ago and now gives 403. The link won't open for me either on my wifi or mobile network.

**Comment by csillaj** [comment]
Hi, this started to happen for me as well all of a sudden. The link returns 403

**Comment by andrisLaduzans** [comment]
+1 
`
    Could not determine the dependencies of task ':customerio-reactnative:compileDebugAidl'.
    > Could not resolve all task dependencies for configuration ':customerio-reactnative:debugCompileClasspath'.
       > Could not resolve build:gist:[3.1,4.0).
     Required by:
             project :customerio-reactnative > io.customer.android:messaging-in-app:3.3.2
          > Failed to list versions for build:gist.
         > Unable to load Maven meta-data from https://maven.gist.build/build/gist/maven-metadata.xml.
            > Could not GET 'https://maven.gist.build/build/gist/maven-metadata.xml'. Received status code 403 from server: Forbidden
          > Failed to list versions for build:gist.
             > Unable to load Maven meta-data from https://maven.gist.build/build/gist/maven-metadata.xml.
                > Could not GET 'https://maven.gist.build/build/gist/maven-metadata.xml'. Received status code 403 from server: Forbidden
`

**Comment by andrisLaduzans** [comment]
@daniel-fs how is this closed? more people reposting same issue

**Comment by mrehan27** [comment]
We have fixed this and should be resolved now. You can keep using the same repository without any issue.

```
maven { url 'https://maven.gist.build' }
```

If you face any issue, please let us know so we can look into it.

**Comment by PaulvanMotman** [comment]
It seems like there is still an issue. I'm now getting:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processProdDebugResources'.
> Could not resolve all task dependencies for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not resolve io.customer.android:tracking:[3.3,4.0).
     Required by:
         project :app > project :customerio-reactnative
      > Failed to list versions for io.customer.android:tracking.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/io/customer/android/tracking/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/io/customer/android/tracking/maven-metadata.xml'. Received status code 503 from server: Service Unavailable`
            
I have tried both 

`maven { url 'https://maven.gist.build' }`

and 

`maven { url 'https://gitlab.com/api/v4/groups/bourbonltd/-/packages/maven' }`

**Comment by mrehan27** [comment]
Hey @PaulvanMotman. I can see `503` being received for customer.io tracking dependency, but the aforementioned dependency is not affected by above shared urls. So this looks like temporary issue with maven service or a network problem. Please follow [these steps](114#issuecomment-1469808629) for fetching repositories again and let us know if the problem persists.

**Comment by PaulvanMotman** [comment]
@mrehan27 Can confirm, working now
