### ISSUE TITLE
Enum PushPermissionStatus 

### ISSUE THREAD

**Issue by MatiasLjubica** [customerio/customerio-reactnative#115]
Hi ! I notice a typo from this Enum, the current value of PushPermissionStatus.NotDetermined is **"NotDetermined"** but the SDK getPushPermissionStatus function return **"Notdetermined"**

```typescript
export declare enum PushPermissionStatus {
    Granted = "Granted",
    Denied = "Denied",
    NotDetermined = "NotDetermined"
}
```

**Comment by ami-aman** [comment]
Hi @MatiasLjubica 
Thank you for pointing out the error. We have opened a PR with the fix, which will be released soon.

**Comment by levibostian** [comment]
This issue has been fixed by our team and is being deployed right now. 

The issue has been resolved by the `getPushPermissionStatus` function return `NotDetermined`, as expected by the enum `PushPermissionStatus`.

**Comment by levibostian** [comment]
Fix released to `2.2.1`

**Comment by kuldip-simform** [comment]
looks like this is still not fixed.
still code is like this in below file.

https://github.com/customerio/customerio-reactnative/blob/main/src/types/PushPermissionStatus.tsx

```JS
export enum PushPermissionStatus {
  Granted = 'Granted',
  Denied = 'Denied',
  NotDetermined = 'NotDetermined',
}
```
