### ISSUE TITLE
Customer io crashes Webview

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#133]
Hi,
After long waiting of stabilizing this package, I decided to integrate it into my app.
Now after spending tonnes of hours I finally found out that the issue that crashes my app is this library and not Webview:
https://github.com/react-native-webview/react-native-webview/issues/2948
Please Fix it as I'm always facing some blockers when I'm trying to use this library and getting tired of it.
With a glance, I wasn't able to find anything suspicious in the Android directory but for sure there is something.

Thanks and waiting for a solution.

**Comment by Shahroz16** [comment]
Hey folks, apologies for the issue. We will be looking into it, CustomerIO SDKs are using web views internally for in-app messages and seems like somehow `react-native-webview` is clashing with the webview that is being used in the CIO SDK. 

Please disable the in-app to avoid the crash, will update as soon as its fixed. Thank you again for your patience.

**Comment by dannyhw** [comment]
Thanks @Shahroz16, will disable for now 👍

**Comment by richardkuiper** [comment]
Thanks. Looking forward to the fix.

**Comment by Shahroz16** [comment]
Hey folks, glad to inform you this has been fixed and rolled out. Just gradle update the dependencies and it should start working. Thank you for your patience and feel free to re-open if you encounter this issue again.

**Comment by beqramo** [comment]
Thanks but I don't see the release. It is still 2.3.3

**Comment by richardkuiper** [comment]
Just checked on 2.3.3 and the problem still exists. @Shahroz16. Should we be using a new version?

**Comment by Shahroz16** [comment]
@richardkuiper 2.3.3 is the latest. Can you delete your node modules and run again. 

Our SDK is setup to auto fetch internal dependencies, so If you can just clear the cache and try again it should work.

**Comment by beqramo** [comment]
So you are saying that RN package will always download up to date versions of native packages?
Hmm I think you need to change this pattern

**Comment by beqramo** [comment]
That make sense then why it was crashed. As i have this package in prod but I don't have error. Errors started last week. So between this time you released new native package update and it crashed the app.

**Comment by richardkuiper** [comment]
@Shahroz16 still not working. I do the following:

- `rm -rf package-lock.json && rm -rf node_modules && cd ios && rm -rf Pods Podfile.lock && cd ..`
- `yarn install && cd ios && pod install && cd ..`
- install app and run

Same error.

**Comment by Shahroz16** [comment]
Can you try `npx react-native run-android`?

**Comment by beqramo** [comment]
I can't check now.
Please change how your are installing native packages. I need stability from this library

**Comment by Shahroz16** [comment]
Yes, of course, we are in the process of setting up pipelines that would ensure that with every native release that goes out, react-native would automatically get tested to ensure nothing breaks. We can even review the decision to auto-update the dependencies as well which would slow the roll-out. But rest assured, stability is our very much focus.

**Comment by richardkuiper** [comment]
> Can you try `npx react-native run-android`?

I am running `yarn react-native run-android`

**Comment by bamboorick** [comment]
So are we solved this issue yet or not ?

**Comment by Shahroz16** [comment]
@bamboorick this issue has been resolved. The issue is the gradle cache in your react native application if you don't find the latest version. 

If you run the command, in your `android` folder

```
./gradlew app:dependencies | pbcopy
```

You will be able to see the dependencies and their versions. In their there will be a `gist` dependency, and it should look like this

```
build:gist:[3.1,4.0) -> 3.2.2
```

If it's anything other than `3.2.2` that means, your application is still using cached dependencies and not fetching the latest ones. You can try running `gradlew build --refresh-dependencies` to force download fresh ones.

**Comment by richardkuiper** [comment]
@Shahroz16 looks to be resolved now. I would recommend not using this approach going forward though.

**Comment by beqramo** [comment]
With full respect, @Shahroz16 no CI/CD pipeline do the flow that we have in the app so please move repo to static versioning this isn't a correct way and i can assure you that it will create problems and even worse crashes in the apps and i really don't want my app to me one of them.
Please think on it one more time.
As you saw one case already happened and unfortunately it will be more and it scares me, I don't want to fork your repo and pull it like that.
